package ru.akimov.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the AttachmentFile service. Represents a row in the &quot;akimov_attachment_files&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.akimov.model.impl.AttachmentFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.akimov.model.impl.AttachmentFileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AttachmentFile
 * @see ru.akimov.model.impl.AttachmentFileImpl
 * @see ru.akimov.model.impl.AttachmentFileModelImpl
 * @generated
 */
public interface AttachmentFileModel extends BaseModel<AttachmentFile> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Вложения model instance should use the {@link AttachmentFile} interface instead.
     */

    /**
     * Returns the primary key of this Вложения.
     *
     * @return the primary key of this Вложения
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this Вложения.
     *
     * @param primaryKey the primary key of this Вложения
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the ID of this Вложения.
     *
     * @return the ID of this Вложения
     */
    public int getId();

    /**
     * Sets the ID of this Вложения.
     *
     * @param id the ID of this Вложения
     */
    public void setId(int id);

    /**
     * Returns the file name of this Вложения.
     *
     * @return the file name of this Вложения
     */
    @AutoEscape
    public String getFileName();

    /**
     * Sets the file name of this Вложения.
     *
     * @param fileName the file name of this Вложения
     */
    public void setFileName(String fileName);

    /**
     * Returns the extension of this Вложения.
     *
     * @return the extension of this Вложения
     */
    @AutoEscape
    public String getExtension();

    /**
     * Sets the extension of this Вложения.
     *
     * @param extension the extension of this Вложения
     */
    public void setExtension(String extension);

    /**
     * Returns the size of this Вложения.
     *
     * @return the size of this Вложения
     */
    public int getSize();

    /**
     * Sets the size of this Вложения.
     *
     * @param size the size of this Вложения
     */
    public void setSize(int size);

    /**
     * Returns the mime type of this Вложения.
     *
     * @return the mime type of this Вложения
     */
    @AutoEscape
    public String getMimeType();

    /**
     * Sets the mime type of this Вложения.
     *
     * @param mimeType the mime type of this Вложения
     */
    public void setMimeType(String mimeType);

    /**
     * Returns the data of this Вложения.
     *
     * @return the data of this Вложения
     */
    public Blob getData();

    /**
     * Sets the data of this Вложения.
     *
     * @param data the data of this Вложения
     */
    public void setData(Blob data);

    /**
     * Returns the uploaded of this Вложения.
     *
     * @return the uploaded of this Вложения
     */
    public Date getUploaded();

    /**
     * Sets the uploaded of this Вложения.
     *
     * @param uploaded the uploaded of this Вложения
     */
    public void setUploaded(Date uploaded);

    /**
     * Returns the user ID of this Вложения.
     *
     * @return the user ID of this Вложения
     */
    public int getUserId();

    /**
     * Sets the user ID of this Вложения.
     *
     * @param userId the user ID of this Вложения
     */
    public void setUserId(int userId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.akimov.model.AttachmentFile attachmentFile);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.akimov.model.AttachmentFile> toCacheModel();

    @Override
    public ru.akimov.model.AttachmentFile toEscapedModel();

    @Override
    public ru.akimov.model.AttachmentFile toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
