package ru.akimov.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AuditEntry service. Represents a row in the &quot;akimov_audit_action_entries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.akimov.model.impl.AuditEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.akimov.model.impl.AuditEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEntry
 * @see ru.akimov.model.impl.AuditEntryImpl
 * @see ru.akimov.model.impl.AuditEntryModelImpl
 * @generated
 */
public interface AuditEntryModel extends BaseModel<AuditEntry> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Запись аудита model instance should use the {@link AuditEntry} interface instead.
     */

    /**
     * Returns the primary key of this Запись аудита.
     *
     * @return the primary key of this Запись аудита
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this Запись аудита.
     *
     * @param primaryKey the primary key of this Запись аудита
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the entry ID of this Запись аудита.
     *
     * @return the entry ID of this Запись аудита
     */
    public int getEntryId();

    /**
     * Sets the entry ID of this Запись аудита.
     *
     * @param entryId the entry ID of this Запись аудита
     */
    public void setEntryId(int entryId);

    /**
     * Returns the entry group ID of this Запись аудита.
     *
     * @return the entry group ID of this Запись аудита
     */
    public int getEntryGroupId();

    /**
     * Sets the entry group ID of this Запись аудита.
     *
     * @param entryGroupId the entry group ID of this Запись аудита
     */
    public void setEntryGroupId(int entryGroupId);

    /**
     * Returns the audit type of this Запись аудита.
     *
     * @return the audit type of this Запись аудита
     */
    @AutoEscape
    public String getAuditType();

    /**
     * Sets the audit type of this Запись аудита.
     *
     * @param auditType the audit type of this Запись аудита
     */
    public void setAuditType(String auditType);

    /**
     * Returns the entity type of this Запись аудита.
     *
     * @return the entity type of this Запись аудита
     */
    @AutoEscape
    public String getEntityType();

    /**
     * Sets the entity type of this Запись аудита.
     *
     * @param entityType the entity type of this Запись аудита
     */
    public void setEntityType(String entityType);

    /**
     * Returns the entity ID of this Запись аудита.
     *
     * @return the entity ID of this Запись аудита
     */
    public int getEntityId();

    /**
     * Sets the entity ID of this Запись аудита.
     *
     * @param entityId the entity ID of this Запись аудита
     */
    public void setEntityId(int entityId);

    /**
     * Returns the metadata of this Запись аудита.
     *
     * @return the metadata of this Запись аудита
     */
    @AutoEscape
    public String getMetadata();

    /**
     * Sets the metadata of this Запись аудита.
     *
     * @param metadata the metadata of this Запись аудита
     */
    public void setMetadata(String metadata);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.akimov.model.AuditEntry auditEntry);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.akimov.model.AuditEntry> toCacheModel();

    @Override
    public ru.akimov.model.AuditEntry toEscapedModel();

    @Override
    public ru.akimov.model.AuditEntry toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
