package ru.akimov.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AuditEntryGroup service. Represents a row in the &quot;akimov_audit_action_groups&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.akimov.model.impl.AuditEntryGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.akimov.model.impl.AuditEntryGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEntryGroup
 * @see ru.akimov.model.impl.AuditEntryGroupImpl
 * @see ru.akimov.model.impl.AuditEntryGroupModelImpl
 * @generated
 */
public interface AuditEntryGroupModel extends BaseModel<AuditEntryGroup> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Группа записей аудита model instance should use the {@link AuditEntryGroup} interface instead.
     */

    /**
     * Returns the primary key of this Группа записей аудита.
     *
     * @return the primary key of this Группа записей аудита
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this Группа записей аудита.
     *
     * @param primaryKey the primary key of this Группа записей аудита
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the entry group ID of this Группа записей аудита.
     *
     * @return the entry group ID of this Группа записей аудита
     */
    public int getEntryGroupId();

    /**
     * Sets the entry group ID of this Группа записей аудита.
     *
     * @param entryGroupId the entry group ID of this Группа записей аудита
     */
    public void setEntryGroupId(int entryGroupId);

    /**
     * Returns the company ID of this Группа записей аудита.
     *
     * @return the company ID of this Группа записей аудита
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this Группа записей аудита.
     *
     * @param companyId the company ID of this Группа записей аудита
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this Группа записей аудита.
     *
     * @return the user ID of this Группа записей аудита
     */
    public long getUserId();

    /**
     * Sets the user ID of this Группа записей аудита.
     *
     * @param userId the user ID of this Группа записей аудита
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this Группа записей аудита.
     *
     * @return the user uuid of this Группа записей аудита
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this Группа записей аудита.
     *
     * @param userUuid the user uuid of this Группа записей аудита
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this Группа записей аудита.
     *
     * @return the user name of this Группа записей аудита
     */
    @AutoEscape
    public String getUserName();

    /**
     * Sets the user name of this Группа записей аудита.
     *
     * @param userName the user name of this Группа записей аудита
     */
    public void setUserName(String userName);

    /**
     * Returns the event date of this Группа записей аудита.
     *
     * @return the event date of this Группа записей аудита
     */
    public Date getEventDate();

    /**
     * Sets the event date of this Группа записей аудита.
     *
     * @param eventDate the event date of this Группа записей аудита
     */
    public void setEventDate(Date eventDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.akimov.model.AuditEntryGroup auditEntryGroup);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.akimov.model.AuditEntryGroup> toCacheModel();

    @Override
    public ru.akimov.model.AuditEntryGroup toEscapedModel();

    @Override
    public ru.akimov.model.AuditEntryGroup toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
