package ru.akimov.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityFieldChange service. Represents a row in the &quot;akimov_audit_field_changes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.akimov.model.impl.EntityFieldChangeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.akimov.model.impl.EntityFieldChangeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityFieldChange
 * @see ru.akimov.model.impl.EntityFieldChangeImpl
 * @see ru.akimov.model.impl.EntityFieldChangeModelImpl
 * @generated
 */
public interface EntityFieldChangeModel extends BaseModel<EntityFieldChange> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a Изменение атрибута сущности model instance should use the {@link EntityFieldChange} interface instead.
     */

    /**
     * Returns the primary key of this Изменение атрибута сущности.
     *
     * @return the primary key of this Изменение атрибута сущности
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this Изменение атрибута сущности.
     *
     * @param primaryKey the primary key of this Изменение атрибута сущности
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the field change ID of this Изменение атрибута сущности.
     *
     * @return the field change ID of this Изменение атрибута сущности
     */
    public int getFieldChangeId();

    /**
     * Sets the field change ID of this Изменение атрибута сущности.
     *
     * @param fieldChangeId the field change ID of this Изменение атрибута сущности
     */
    public void setFieldChangeId(int fieldChangeId);

    /**
     * Returns the entry ID of this Изменение атрибута сущности.
     *
     * @return the entry ID of this Изменение атрибута сущности
     */
    public int getEntryId();

    /**
     * Sets the entry ID of this Изменение атрибута сущности.
     *
     * @param entryId the entry ID of this Изменение атрибута сущности
     */
    public void setEntryId(int entryId);

    /**
     * Returns the field name of this Изменение атрибута сущности.
     *
     * @return the field name of this Изменение атрибута сущности
     */
    @AutoEscape
    public String getFieldName();

    /**
     * Sets the field name of this Изменение атрибута сущности.
     *
     * @param fieldName the field name of this Изменение атрибута сущности
     */
    public void setFieldName(String fieldName);

    /**
     * Returns the old value of this Изменение атрибута сущности.
     *
     * @return the old value of this Изменение атрибута сущности
     */
    @AutoEscape
    public String getOldValue();

    /**
     * Sets the old value of this Изменение атрибута сущности.
     *
     * @param oldValue the old value of this Изменение атрибута сущности
     */
    public void setOldValue(String oldValue);

    /**
     * Returns the new value of this Изменение атрибута сущности.
     *
     * @return the new value of this Изменение атрибута сущности
     */
    @AutoEscape
    public String getNewValue();

    /**
     * Sets the new value of this Изменение атрибута сущности.
     *
     * @param newValue the new value of this Изменение атрибута сущности
     */
    public void setNewValue(String newValue);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.akimov.model.EntityFieldChange entityFieldChange);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.akimov.model.EntityFieldChange> toCacheModel();

    @Override
    public ru.akimov.model.EntityFieldChange toEscapedModel();

    @Override
    public ru.akimov.model.EntityFieldChange toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
