package ru.isands.akimov.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.isands.akimov.model.EntityFieldChange;
import ru.isands.akimov.service.EntityFieldChangeLocalServiceUtil;

/**
 * The extended model base implementation for the EntityFieldChange service. Represents a row in the &quot;akimov_entity_field_change&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityFieldChangeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityFieldChangeImpl
 * @see ru.isands.akimov.model.EntityFieldChange
 * @generated
 */
public abstract class EntityFieldChangeBaseImpl
    extends EntityFieldChangeModelImpl implements EntityFieldChange {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity field change model instance should use the {@link EntityFieldChange} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityFieldChangeLocalServiceUtil.addEntityFieldChange(this);
        } else {
            EntityFieldChangeLocalServiceUtil.updateEntityFieldChange(this);
        }
    }
}
