package ru.isands.akimov.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EntityEditingHistory service. Represents a row in the &quot;akimov_entity_editing_history&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.isands.akimov.model.impl.EntityEditingHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.isands.akimov.model.impl.EntityEditingHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityEditingHistory
 * @see ru.isands.akimov.model.impl.EntityEditingHistoryImpl
 * @see ru.isands.akimov.model.impl.EntityEditingHistoryModelImpl
 * @generated
 */
public interface EntityEditingHistoryModel extends BaseModel<EntityEditingHistory> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity editing history model instance should use the {@link EntityEditingHistory} interface instead.
     */

    /**
     * Returns the primary key of this entity editing history.
     *
     * @return the primary key of this entity editing history
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this entity editing history.
     *
     * @param primaryKey the primary key of this entity editing history
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the ID of this entity editing history.
     *
     * @return the ID of this entity editing history
     */
    public int getId();

    /**
     * Sets the ID of this entity editing history.
     *
     * @param id the ID of this entity editing history
     */
    public void setId(int id);

    /**
     * Returns the entity ID of this entity editing history.
     *
     * @return the entity ID of this entity editing history
     */
    public int getEntityId();

    /**
     * Sets the entity ID of this entity editing history.
     *
     * @param entityId the entity ID of this entity editing history
     */
    public void setEntityId(int entityId);

    /**
     * Returns the entity type of this entity editing history.
     *
     * @return the entity type of this entity editing history
     */
    @AutoEscape
    public String getEntityType();

    /**
     * Sets the entity type of this entity editing history.
     *
     * @param entityType the entity type of this entity editing history
     */
    public void setEntityType(String entityType);

    /**
     * Returns the user ID of this entity editing history.
     *
     * @return the user ID of this entity editing history
     */
    public long getUserId();

    /**
     * Sets the user ID of this entity editing history.
     *
     * @param userId the user ID of this entity editing history
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this entity editing history.
     *
     * @return the user uuid of this entity editing history
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this entity editing history.
     *
     * @param userUuid the user uuid of this entity editing history
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the description of this entity editing history.
     *
     * @return the description of this entity editing history
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this entity editing history.
     *
     * @param description the description of this entity editing history
     */
    public void setDescription(String description);

    /**
     * Returns the date of change of this entity editing history.
     *
     * @return the date of change of this entity editing history
     */
    public Date getDateOfChange();

    /**
     * Sets the date of change of this entity editing history.
     *
     * @param dateOfChange the date of change of this entity editing history
     */
    public void setDateOfChange(Date dateOfChange);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        ru.isands.akimov.model.EntityEditingHistory entityEditingHistory);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.isands.akimov.model.EntityEditingHistory> toCacheModel();

    @Override
    public ru.isands.akimov.model.EntityEditingHistory toEscapedModel();

    @Override
    public ru.isands.akimov.model.EntityEditingHistory toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
