package ru.akimov.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.akimov.model.AttachmentFile;

import ru.akimov.service.AttachmentFileLocalServiceUtil;

/**
 * The extended model base implementation for the AttachmentFile service. Represents a row in the &quot;akimov_attachment_files&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AttachmentFileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AttachmentFileImpl
 * @see ru.akimov.model.AttachmentFile
 * @generated
 */
public abstract class AttachmentFileBaseImpl extends AttachmentFileModelImpl
    implements AttachmentFile {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Вложения model instance should use the {@link AttachmentFile} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AttachmentFileLocalServiceUtil.addAttachmentFile(this);
        } else {
            AttachmentFileLocalServiceUtil.updateAttachmentFile(this);
        }
    }
}
