package ru.akimov.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import ru.akimov.model.AuditEntry;
import ru.akimov.model.AuditEntryModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AuditEntry service. Represents a row in the &quot;akimov_audit_action_entries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ru.akimov.model.AuditEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEntryImpl
 * @see ru.akimov.model.AuditEntry
 * @see ru.akimov.model.AuditEntryModel
 * @generated
 */
public class AuditEntryModelImpl extends BaseModelImpl<AuditEntry>
    implements AuditEntryModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Запись аудита model instance should use the {@link ru.akimov.model.AuditEntry} interface instead.
     */
    public static final String TABLE_NAME = "akimov_audit_action_entries";
    public static final Object[][] TABLE_COLUMNS = {
            { "entryId", Types.INTEGER },
            { "entryGroupId", Types.INTEGER },
            { "auditType", Types.VARCHAR },
            { "entityType", Types.VARCHAR },
            { "entityId", Types.INTEGER },
            { "metadata", Types.CLOB }
        };
    public static final String TABLE_SQL_CREATE = "create table akimov_audit_action_entries (entryId INTEGER not null primary key,entryGroupId INTEGER,auditType VARCHAR(75) null,entityType VARCHAR(75) null,entityId INTEGER,metadata TEXT null)";
    public static final String TABLE_SQL_DROP = "drop table akimov_audit_action_entries";
    public static final String ORDER_BY_JPQL = " ORDER BY auditEntry.entryId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY akimov_audit_action_entries.entryId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.ru.akimov.model.AuditEntry"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.ru.akimov.model.AuditEntry"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.ru.akimov.model.AuditEntry"),
            true);
    public static long ENTRYGROUPID_COLUMN_BITMASK = 1L;
    public static long ENTRYID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.ru.akimov.model.AuditEntry"));
    private static ClassLoader _classLoader = AuditEntry.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            AuditEntry.class
        };
    private int _entryId;
    private int _entryGroupId;
    private int _originalEntryGroupId;
    private boolean _setOriginalEntryGroupId;
    private String _auditType;
    private String _entityType;
    private int _entityId;
    private String _metadata;
    private long _columnBitmask;
    private AuditEntry _escapedModel;

    public AuditEntryModelImpl() {
    }

    @Override
    public int getPrimaryKey() {
        return _entryId;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setEntryId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _entryId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return AuditEntry.class;
    }

    @Override
    public String getModelClassName() {
        return AuditEntry.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("entryId", getEntryId());
        attributes.put("entryGroupId", getEntryGroupId());
        attributes.put("auditType", getAuditType());
        attributes.put("entityType", getEntityType());
        attributes.put("entityId", getEntityId());
        attributes.put("metadata", getMetadata());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer entryId = (Integer) attributes.get("entryId");

        if (entryId != null) {
            setEntryId(entryId);
        }

        Integer entryGroupId = (Integer) attributes.get("entryGroupId");

        if (entryGroupId != null) {
            setEntryGroupId(entryGroupId);
        }

        String auditType = (String) attributes.get("auditType");

        if (auditType != null) {
            setAuditType(auditType);
        }

        String entityType = (String) attributes.get("entityType");

        if (entityType != null) {
            setEntityType(entityType);
        }

        Integer entityId = (Integer) attributes.get("entityId");

        if (entityId != null) {
            setEntityId(entityId);
        }

        String metadata = (String) attributes.get("metadata");

        if (metadata != null) {
            setMetadata(metadata);
        }
    }

    @Override
    public int getEntryId() {
        return _entryId;
    }

    @Override
    public void setEntryId(int entryId) {
        _entryId = entryId;
    }

    @Override
    public int getEntryGroupId() {
        return _entryGroupId;
    }

    @Override
    public void setEntryGroupId(int entryGroupId) {
        _columnBitmask |= ENTRYGROUPID_COLUMN_BITMASK;

        if (!_setOriginalEntryGroupId) {
            _setOriginalEntryGroupId = true;

            _originalEntryGroupId = _entryGroupId;
        }

        _entryGroupId = entryGroupId;
    }

    public int getOriginalEntryGroupId() {
        return _originalEntryGroupId;
    }

    @Override
    public String getAuditType() {
        if (_auditType == null) {
            return StringPool.BLANK;
        } else {
            return _auditType;
        }
    }

    @Override
    public void setAuditType(String auditType) {
        _auditType = auditType;
    }

    @Override
    public String getEntityType() {
        if (_entityType == null) {
            return StringPool.BLANK;
        } else {
            return _entityType;
        }
    }

    @Override
    public void setEntityType(String entityType) {
        _entityType = entityType;
    }

    @Override
    public int getEntityId() {
        return _entityId;
    }

    @Override
    public void setEntityId(int entityId) {
        _entityId = entityId;
    }

    @Override
    public String getMetadata() {
        if (_metadata == null) {
            return StringPool.BLANK;
        } else {
            return _metadata;
        }
    }

    @Override
    public void setMetadata(String metadata) {
        _metadata = metadata;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public AuditEntry toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (AuditEntry) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        AuditEntryImpl auditEntryImpl = new AuditEntryImpl();

        auditEntryImpl.setEntryId(getEntryId());
        auditEntryImpl.setEntryGroupId(getEntryGroupId());
        auditEntryImpl.setAuditType(getAuditType());
        auditEntryImpl.setEntityType(getEntityType());
        auditEntryImpl.setEntityId(getEntityId());
        auditEntryImpl.setMetadata(getMetadata());

        auditEntryImpl.resetOriginalValues();

        return auditEntryImpl;
    }

    @Override
    public int compareTo(AuditEntry auditEntry) {
        int primaryKey = auditEntry.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof AuditEntry)) {
            return false;
        }

        AuditEntry auditEntry = (AuditEntry) obj;

        int primaryKey = auditEntry.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        AuditEntryModelImpl auditEntryModelImpl = this;

        auditEntryModelImpl._originalEntryGroupId = auditEntryModelImpl._entryGroupId;

        auditEntryModelImpl._setOriginalEntryGroupId = false;

        auditEntryModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<AuditEntry> toCacheModel() {
        AuditEntryCacheModel auditEntryCacheModel = new AuditEntryCacheModel();

        auditEntryCacheModel.entryId = getEntryId();

        auditEntryCacheModel.entryGroupId = getEntryGroupId();

        auditEntryCacheModel.auditType = getAuditType();

        String auditType = auditEntryCacheModel.auditType;

        if ((auditType != null) && (auditType.length() == 0)) {
            auditEntryCacheModel.auditType = null;
        }

        auditEntryCacheModel.entityType = getEntityType();

        String entityType = auditEntryCacheModel.entityType;

        if ((entityType != null) && (entityType.length() == 0)) {
            auditEntryCacheModel.entityType = null;
        }

        auditEntryCacheModel.entityId = getEntityId();

        auditEntryCacheModel.metadata = getMetadata();

        String metadata = auditEntryCacheModel.metadata;

        if ((metadata != null) && (metadata.length() == 0)) {
            auditEntryCacheModel.metadata = null;
        }

        return auditEntryCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(13);

        sb.append("{entryId=");
        sb.append(getEntryId());
        sb.append(", entryGroupId=");
        sb.append(getEntryGroupId());
        sb.append(", auditType=");
        sb.append(getAuditType());
        sb.append(", entityType=");
        sb.append(getEntityType());
        sb.append(", entityId=");
        sb.append(getEntityId());
        sb.append(", metadata=");
        sb.append(getMetadata());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(22);

        sb.append("<model><model-name>");
        sb.append("ru.akimov.model.AuditEntry");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>entryId</column-name><column-value><![CDATA[");
        sb.append(getEntryId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>entryGroupId</column-name><column-value><![CDATA[");
        sb.append(getEntryGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>auditType</column-name><column-value><![CDATA[");
        sb.append(getAuditType());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>entityType</column-name><column-value><![CDATA[");
        sb.append(getEntityType());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>entityId</column-name><column-value><![CDATA[");
        sb.append(getEntityId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>metadata</column-name><column-value><![CDATA[");
        sb.append(getMetadata());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
