package ru.akimov.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.akimov.model.AuditEntryGroup;

import ru.akimov.service.AuditEntryGroupLocalServiceUtil;

/**
 * The extended model base implementation for the AuditEntryGroup service. Represents a row in the &quot;akimov_audit_action_groups&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditEntryGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEntryGroupImpl
 * @see ru.akimov.model.AuditEntryGroup
 * @generated
 */
public abstract class AuditEntryGroupBaseImpl extends AuditEntryGroupModelImpl
    implements AuditEntryGroup {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a Группа записей аудита model instance should use the {@link AuditEntryGroup} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AuditEntryGroupLocalServiceUtil.addAuditEntryGroup(this);
        } else {
            AuditEntryGroupLocalServiceUtil.updateAuditEntryGroup(this);
        }
    }
}
